version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build: .
    container_name: go-app
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - RATE_LIMIT_IP=5
      - RATE_LIMIT_TOKEN=10
      - BLOCK_TIME=300
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
